name: Deploy to Minikube using GitHub Actions

on: [push]
  
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build Node.js Docker Image
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
       node-Version: 16.X
       cache: "npm"
    - run: npm install
    - name: Login tp Docker Hub
      uses: docker/login-action@v2
      with:
        username: "gopi123321"
        password: "Lanka@143"
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: gopi123321/app
